# Generated by Django 3.1.5 on 2021-02-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(default=models.TextField(blank=True, null=True), max_length=255),
        ),
    ]
