# Generated by Django 3.1.5 on 2021-02-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0004_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
