# Generated by Django 3.1.5 on 2021-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0005_product_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='primary',
                                   max_length=1),
        ),
    ]
