# Generated by Django 3.1.5 on 2021-02-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0011_auto_20210208_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=50), max_length=100),
        ),
    ]
