# Generated by Django 3.1.5 on 2021-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0012_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
