# Generated by Django 3.1.5 on 2021-02-08 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0013_auto_20210208_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products',
                                    to='product.product'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
