# Generated by Django 3.1.7 on 2021-02-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210225_1626'),
        ('product', '0014_auto_20210208_1040'),
    ]

    operations = [
    ]
